Feature/users controller
dbyington/bravakin-server pull request #1
Opened 2017-08-14 14:37 UTC by angelicavalenta

created user controllers

2017-08-14 14:49 UTC, dbyington commented on router.js
> +const router = require('koa-router')();
add 'use strict'

2017-08-14 14:49 UTC, dbyington commented on index.js
> +const Koa = require('koa');
add 'use strict'

2017-08-14 14:50 UTC, dbyington submitted a review, later dismissed
This is the a pull that includes the status thus far.
There are perhaps something that should be in separate commit/pulls but due to interdependencies it took a lot of extra changes/files to get to a good point to commit, push, and submit the pull request.
There are a couple "housekeeping" items I commented inline.

2017-08-14 14:52 UTC, dbyington reviewed
This is the a pull that includes the status thus far.
There are perhaps something that should be in separate commit/pulls but due to interdependencies it took a lot of extra changes/files to get to a good point to commit, push, and submit the pull request.
There are a couple "housekeeping" items I commented inline.

2017-08-14 17:02 UTC, arol requested changes

2017-08-14 17:02 UTC, arol commented on controllers/users.controller.js
> +  const user = await getFilteredUser(ctx.status.accessToken);
It sounds like a middleware to me 🤔

2017-08-14 17:02 UTC, arol commented on controllers/users.controller.js
> +  ctx.body = user;
In this case, rely on `getFilteredUser` middleware as usual, and use a serializer to print your user.

`ctx.body = UserSerializer.serialize(user)`

A serializer is a function that takes a model and responds with secure-to-print object representing the instance.

2017-08-16 13:32 UTC, dbyington commented
stale

2017-08-16 13:32 UTC, closed without merging