Fix/users controller
dbyington/bravakin-server pull request #2
Opened 2017-08-15 15:21 UTC by dbyington

This is tests and code for the users controller.
As an aside two middlewares were created as dependencies.

2017-08-15 15:34 UTC, angelicavalenta approved these changes

2017-08-16 12:52 UTC, arol requested changes

2017-08-16 12:52 UTC, arol commented on middlewares/authentication.js
> +const CLIENT_SECRET = 'b5466dfe3a7f470180f8148345bb67db';
🙌

2017-08-16 12:52 UTC, arol commented on middlewares/authentication.js
> +    redirect_uri = 'https://me/authorize',
Add this on the environment variables (`dotenv`?)

2017-08-16 12:52 UTC, arol commented on middlewares/user-serializer.js
> +'use strict';
This is an utility (utils), not a middleware.

2017-08-16 12:52 UTC, arol commented on middlewares/user-serializer.js
> +'use strict';
Or you can place them (this and future serializers) on the a new serializers folder.

2017-08-16 12:52 UTC, arol commented on models/media.model.js
> +});
Create the model and export it.

2017-08-16 12:52 UTC, arol commented on test/controllers.test.js
> +      let ctx = Object.assign({}, mocks.ctx, {state: {accessToken: 'ACCESS_TOKEN'}})
Same preparation as the last case: use `beforeAll`

2017-08-16 12:52 UTC, arol commented on test/controllers.test.js
> +      await users.handleUserGet(ctx);
Same here (`beforeAll`)

2017-08-16 13:35 UTC, dbyington commented
Changes made in commit eebb7f0

2017-08-16 13:42 UTC, arol approved these changes

2017-08-16 13:48 UTC, merged